stages: [validate, build]

server_build:
  stage: validate
  image: node:22-alpine
  script:
    - cd server
    - npm ci
    - npm run build

server_test:
  stage: validate
  image: node:22-alpine
  script:
    - cd server
    - npm ci
    - npm run build
    - node --version

desktop_build:
  stage: build
  image: node:22-bookworm
  script:
    - cd desktop
    - npm ci
    - npm run check
    - npm run build
