CREATE EXTENSION IF NOT EXISTS pgcrypto;
CREATE TABLE IF NOT EXISTS users(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),name text NOT NULL,phone text UNIQUE,email text UNIQUE,password_hash text NOT NULL,role text NOT NULL CHECK(role IN ('ADMIN','LEADER','COORDINATOR','SEARCHER','VIEWER')),active boolean NOT NULL DEFAULT true,created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS searches(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),title text NOT NULL,status text NOT NULL DEFAULT 'PLANNED' CHECK(status IN ('PLANNED','ACTIVE','PAUSED','COMPLETED','CANCELLED')),area text,description text,incident_lat double precision,incident_lng double precision,created_by uuid REFERENCES users(id),started_at timestamptz,ended_at timestamptz,created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS search_members(search_id uuid REFERENCES searches(id) ON DELETE CASCADE,user_id uuid REFERENCES users(id) ON DELETE CASCADE,joined_at timestamptz NOT NULL DEFAULT now(),PRIMARY KEY(search_id,user_id));
CREATE TABLE IF NOT EXISTS tasks(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),search_id uuid NOT NULL REFERENCES searches(id) ON DELETE CASCADE,assignee_id uuid REFERENCES users(id),created_by uuid REFERENCES users(id),title text NOT NULL,description text,status text NOT NULL DEFAULT 'OPEN' CHECK(status IN ('OPEN','IN_PROGRESS','DONE','CANCELLED')),priority int NOT NULL DEFAULT 2 CHECK(priority BETWEEN 1 AND 3),lat double precision,lng double precision,created_at timestamptz NOT NULL DEFAULT now(),completed_at timestamptz);
CREATE TABLE IF NOT EXISTS events(id bigserial PRIMARY KEY,search_id uuid REFERENCES searches(id) ON DELETE CASCADE,user_id uuid REFERENCES users(id),type text NOT NULL,payload jsonb NOT NULL DEFAULT '{}',created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS gps_points(id bigserial PRIMARY KEY,search_id uuid NOT NULL REFERENCES searches(id) ON DELETE CASCADE,user_id uuid NOT NULL REFERENCES users(id),lat double precision NOT NULL,lng double precision NOT NULL,accuracy double precision,altitude double precision,speed double precision,recorded_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS sessions(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),user_id uuid NOT NULL REFERENCES users(id) ON DELETE CASCADE,token_hash text NOT NULL,expires_at timestamptz NOT NULL,created_at timestamptz NOT NULL DEFAULT now());
CREATE INDEX IF NOT EXISTS idx_searches_status ON searches(status);CREATE INDEX IF NOT EXISTS idx_tasks_search ON tasks(search_id);CREATE INDEX IF NOT EXISTS idx_events_search ON events(search_id);CREATE INDEX IF NOT EXISTS idx_gps_search_time ON gps_points(search_id,recorded_at);CREATE INDEX IF NOT EXISTS idx_gps_user_time ON gps_points(user_id,recorded_at);CREATE INDEX IF NOT EXISTS idx_sessions_user ON sessions(user_id);
