import { FastifyPluginAsync } from 'fastify';
import { z } from 'zod';
import { pool } from '../config.js';
import { auth, parseId, requireSearchAccess } from '../http.js';

const gpsRoutes: FastifyPluginAsync = async (app) => {
  app.post('/api/v1/searches/:id/gps',{preHandler:auth},async(req)=>{const id=parseId(req);await requireSearchAccess(req,id);const b=z.object({points:z.array(z.object({lat:z.number().min(-90).max(90),lng:z.number().min(-180).max(180),accuracy:z.number().nonnegative().optional(),altitude:z.number().optional(),speed:z.number().nonnegative().optional(),recorded_at:z.string().datetime().optional()})).min(1).max(1000)}).parse(req.body);const client=await pool.connect();try{await client.query('BEGIN');for(const p of b.points)await client.query('INSERT INTO gps_points(search_id,user_id,lat,lng,accuracy,altitude,speed,recorded_at) VALUES($1,$2,$3,$4,$5,$6,$7,COALESCE($8,now()))',[id,req.user.id,p.lat,p.lng,p.accuracy??null,p.altitude??null,p.speed??null,p.recorded_at??null]);await client.query('COMMIT');}catch(e){await client.query('ROLLBACK');throw e;}finally{client.release();}return {ok:true,count:b.points.length};});
  app.get('/api/v1/searches/:id/gps',{preHandler:auth},async(req)=>{const id=parseId(req);await requireSearchAccess(req,id);const q=z.object({since:z.string().datetime().optional(),userId:z.string().uuid().optional(),limit:z.coerce.number().int().min(1).max(10000).default(5000)}).parse(req.query);return (await pool.query(`SELECT g.*,u.name user_name FROM gps_points g JOIN users u ON u.id=g.user_id WHERE g.search_id=$1 AND ($2::timestamptz IS NULL OR g.recorded_at>=$2) AND ($3::uuid IS NULL OR g.user_id=$3) ORDER BY g.recorded_at LIMIT $4`,[id,q.since??null,q.userId??null,q.limit])).rows;});
  app.get('/api/v1/searches/:id/snapshot',{preHandler:auth},async(req)=>{const id=parseId(req);await requireSearchAccess(req,id);const [search,members,tasks,events,gps]=await Promise.all([pool.query('SELECT * FROM searches WHERE id=$1',[id]),pool.query('SELECT u.id,u.name,u.role,m.joined_at FROM search_members m JOIN users u ON u.id=m.user_id WHERE m.search_id=$1',[id]),pool.query('SELECT * FROM tasks WHERE search_id=$1 ORDER BY created_at',[id]),pool.query('SELECT e.*,u.name user_name FROM events e LEFT JOIN users u ON u.id=e.user_id WHERE e.search_id=$1 ORDER BY e.created_at DESC LIMIT 200',[id]),pool.query('SELECT g.*,u.name user_name FROM gps_points g JOIN users u ON u.id=g.user_id WHERE g.search_id=$1 ORDER BY g.recorded_at DESC LIMIT 5000',[id])]);return {search:search.rows[0],members:members.rows,tasks:tasks.rows,events:events.rows,gps:gps.rows};});
};

export default gpsRoutes;
