import { FastifyPluginAsync } from 'fastify';
import { httpErrors } from '@fastify/sensible';
import { z } from 'zod';
import { managementRoles, privilegedRoles } from '../rbac.js';
import { pool } from '../config.js';
import { audit, auth, parseId, requireSearchAccess, requireSearchManagement, roles } from '../http.js';

const taskRoutes: FastifyPluginAsync = async (app) => {
  app.get('/api/v1/searches/:id/tasks',{preHandler:auth},async(req)=>{const id=parseId(req);await requireSearchAccess(req,id);return (await pool.query('SELECT t.*,u.name assignee FROM tasks t LEFT JOIN users u ON u.id=t.assignee_id WHERE t.search_id=$1 ORDER BY t.status,t.priority,t.created_at',[id])).rows;});
  app.post('/api/v1/searches/:id/tasks',{preHandler:roles(...managementRoles)},async(req)=>{const id=parseId(req);await requireSearchManagement(req,id);const b=z.object({title:z.string().min(2),description:z.string().optional(),assigneeId:z.string().uuid().optional(),priority:z.number().int().min(1).max(3).default(2),lat:z.number().min(-90).max(90).optional(),lng:z.number().min(-180).max(180).optional()}).parse(req.body);if(b.assigneeId){const member=await pool.query('SELECT 1 FROM search_members WHERE search_id=$1 AND user_id=$2',[id,b.assigneeId]);if(!member.rowCount) throw httpErrors.badRequest('Assignee must be a member of the search');}const r=await pool.query('INSERT INTO tasks(search_id,title,description,assignee_id,priority,lat,lng,created_by) VALUES($1,$2,$3,$4,$5,$6,$7,$8) RETURNING *',[id,b.title,b.description??null,b.assigneeId??null,b.priority,b.lat??null,b.lng??null,req.user.id]);await audit(id,req.user.id,'TASK_CREATED',{taskId:r.rows[0].id});return r.rows[0];});
  app.patch('/api/v1/tasks/:id',{preHandler:auth},async(req)=>{const id=parseId(req);const b=z.object({status:z.enum(['OPEN','IN_PROGRESS','DONE','CANCELLED']).optional(),assigneeId:z.string().uuid().nullable().optional(),description:z.string().optional(),priority:z.number().int().min(1).max(3).optional()}).parse(req.body);const current=await pool.query('SELECT * FROM tasks WHERE id=$1',[id]);if(!current.rowCount)throw httpErrors.notFound('Task not found');const task=current.rows[0];await requireSearchAccess(req,task.search_id);const privileged=privilegedRoles.includes(req.user.role);const manager=managementRoles.includes(req.user.role);if(!privileged&&!manager){if(req.user.role!=='SEARCHER'||task.assignee_id!==req.user.id)throw httpErrors.forbidden('You may only update tasks assigned to you');if(b.assigneeId!==undefined||b.priority!==undefined)throw httpErrors.forbidden('Searchers cannot reassign or reprioritize tasks');}if(b.assigneeId){const member=await pool.query('SELECT 1 FROM search_members WHERE search_id=$1 AND user_id=$2',[task.search_id,b.assigneeId]);if(!member.rowCount)throw httpErrors.badRequest('Assignee must be a member of the search');}const r=await pool.query(`UPDATE tasks SET status=COALESCE($1,status),assignee_id=CASE WHEN $6=true THEN NULL WHEN $2::uuid IS NOT NULL THEN $2::uuid ELSE assignee_id END,description=COALESCE($3,description),priority=COALESCE($4,priority),completed_at=CASE WHEN $1='DONE' THEN now() WHEN $1 IS NOT NULL THEN NULL ELSE completed_at END WHERE id=$5 RETURNING *`,[b.status??null,b.assigneeId??null,b.description??null,b.priority??null,id,b.assigneeId===null]);await audit(task.search_id,req.user.id,'TASK_UPDATED',{taskId:id,changes:b});return r.rows[0];});
};

export default taskRoutes;
