import 'dart:async';
import 'package:flutter/material.dart';
import 'package:geolocator/geolocator.dart';
import 'package:connectivity_plus/connectivity_plus.dart';
import 'package:flutter_map/flutter_map.dart';
import 'package:latlong2/latlong.dart';
import 'package:shared_preferences/shared_preferences.dart';
import 'services/api.dart';
import 'storage/local_db.dart';
const apiUrl=String.fromEnvironment('API_URL',defaultValue:'http://10.0.2.2:8080/api/v1');
void main()=>runApp(const KuKLA());
class KuKLA extends StatelessWidget{const KuKLA({super.key});@override Widget build(BuildContext c)=>MaterialApp(debugShowCheckedModeBanner:false,title:'KuKLA',theme:ThemeData(useMaterial3:true,colorSchemeSeed:Colors.red,brightness:Brightness.dark),home:const LoginScreen());}
class LoginScreen extends StatefulWidget{const LoginScreen({super.key});@override State<LoginScreen> createState()=>_LoginState();}
class _LoginState extends State<LoginScreen>{final login=TextEditingController(text:'searcher@kukla.local'),pass=TextEditingController(text:'searcher123');final api=Api(apiUrl);String? error;bool busy=false;@override Widget build(BuildContext c)=>Scaffold(body:Center(child:SingleChildScrollView(padding:const EdgeInsets.all(28),child:ConstrainedBox(constraints:const BoxConstraints(maxWidth:420),child:Column(children:[const Text('KuKLA',style:TextStyle(fontSize:44,fontWeight:FontWeight.w900)),const Text('Мобильный клиент поисковой группы'),const SizedBox(height:28),TextField(controller:login,decoration:const InputDecoration(labelText:'Email / телефон',border:OutlineInputBorder())),const SizedBox(height:12),TextField(controller:pass,obscureText:true,decoration:const InputDecoration(labelText:'Пароль',border:OutlineInputBorder())),const SizedBox(height:18),SizedBox(width:double.infinity,child:FilledButton(onPressed:busy?null:()async{setState(()=>busy=true);try{final u=await api.login(login.text,pass.text);final sp=await SharedPreferences.getInstance();await sp.setString('token',api.token!);if(!c.mounted)return;Navigator.pushReplacement(c,MaterialPageRoute(builder:(_)=>Home(api:api,user:u)));}catch(e){setState(()=>error='Не удалось войти');}finally{if(mounted)setState(()=>busy=false);}},child:Text(busy?'Вход...':'Войти'))),if(error!=null)Padding(padding:const EdgeInsets.only(top:10),child:Text(error!,style:const TextStyle(color:Colors.redAccent)))]))));}
}
class Home extends StatefulWidget{final Api api;final Map<String,dynamic> user;const Home({super.key,required this.api,required this.user});@override State<Home> createState()=>_HomeState();}
class _HomeState extends State<Home>{final db=LocalDb();late Future<List<dynamic>> searches;Timer? sync;@override void initState(){super.initState();load();sync=Timer.periodic(const Duration(seconds:20),(_)=>syncQueue());}void dispose(){sync?.cancel();super.dispose();}void load(){searches=_loadSearches();}
Future<List<dynamic>> _loadSearches() async {try{final x=await widget.api.searches();await db.put('searches',x);return x;}catch(_){final cached=await db.get('searches');return cached is List?cached:<dynamic>[];}}Future<void> syncQueue()async{final q=await db.queue();for(final item in q){try{final p=Map<String,dynamic>.from(item['payload']);if(item['type']=='gps')await widget.api.sendGps(p['searchId'],List<Map<String,dynamic>>.from(p['points']));if(item['type']=='task')await widget.api.taskStatus(p['taskId'],p['status']);await db.remove(item['id'] as int);}catch(_){break;}}}void refresh(){setState(load);syncQueue();}
@override Widget build(BuildContext c)=>Scaffold(appBar:AppBar(title:const Text('Активные поиски'),actions:[IconButton(onPressed:refresh,icon:const Icon(Icons.sync))]),body:FutureBuilder<List<dynamic>>(future:searches,builder:(c,s){if(!s.hasData)return const Center(child:CircularProgressIndicator());final data=s.data!;if(data.isEmpty)return const Center(child:Text('Активных поисков нет'));return RefreshIndicator(onRefresh:()async{refresh();await searches;},child:ListView.builder(padding:const EdgeInsets.all(12),itemCount:data.length,itemBuilder:(c,i){final x=Map<String,dynamic>.from(data[i]);return Card(child:ListTile(title:Text(x['title']),subtitle:Text('${x['status']} · ${x['area']??'район не указан'}'),trailing:FilledButton(onPressed:()=>Navigator.push(c,MaterialPageRoute(builder:(_)=>SearchScreen(api:widget.api,db:db,search:x))),child:const Text('Открыть'))));}));}));}
}
class SearchScreen extends StatefulWidget{final Api api;final LocalDb db;final Map<String,dynamic> search;const SearchScreen({super.key,required this.api,required this.db,required this.search});@override State<SearchScreen> createState()=>_SearchState();}
class _SearchState extends State<SearchScreen>{List<dynamic> tasks=[];List<dynamic> gps=[];bool tracking=false;StreamSubscription<Position>? sub;@override void initState(){super.initState();load();}Future<void> load()async{try{tasks=await widget.api.tasks(widget.search['id']);gps=await widget.api.gps(widget.search['id']);}catch(_){tasks=(await widget.db.get('tasks:${widget.search['id']}')??[]) as List<dynamic>;}if(mounted)setState((){});}Future<void> join()async{try{await widget.api.join(widget.search['id']);if(mounted)ScaffoldMessenger.of(context).showSnackBar(const SnackBar(content:Text('Вы присоединились к поиску')));}catch(_){}}Future<void> toggleTrack()async{if(tracking){await sub?.cancel();setState(()=>tracking=false);return;}var p=await Geolocator.checkPermission();if(p==LocationPermission.denied)p=await Geolocator.requestPermission();if(p==LocationPermission.denied||p==LocationPermission.deniedForever)return;setState(()=>tracking=true);sub=Geolocator.getPositionStream(locationSettings:const LocationSettings(accuracy:LocationAccuracy.high,distanceFilter:20)).listen((p)async{final point={'lat':p.latitude,'lng':p.longitude,'accuracy':p.accuracy,'altitude':p.altitude,'speed':p.speed,'recorded_at':DateTime.now().toUtc().toIso8601String()};try{await widget.api.sendGps(widget.search['id'],[point]);}catch(_){await widget.db.enqueue('gps',{'searchId':widget.search['id'],'points':[point]});}});}
@override void dispose(){sub?.cancel();super.dispose();}@override Widget build(BuildContext c){final center=LatLng((widget.search['incident_lat']??54.99)*1.0,(widget.search['incident_lng']??73.32)*1.0);final line=gps.map((x)=>LatLng(x['lat']*1.0,x['lng']*1.0)).toList();return Scaffold(appBar:AppBar(title:Text(widget.search['title'])),body:ListView(padding:const EdgeInsets.all(12),children:[SizedBox(height:300,child:FlutterMap(options:MapOptions(initialCenter:center,initialZoom:11),children:[TileLayer(urlTemplate:'https://tile.openstreetmap.org/{z}/{x}/{y}.png',userAgentPackageName:'ru.kukla.mobile'),MarkerLayer(markers:[Marker(point:center,width:40,height:40,child:const Icon(Icons.location_on,color:Colors.red,size:40))]),if(line.length>1)PolylineLayer(polylines:[Polyline(points:line,strokeWidth:4,color:Colors.red)])])),const SizedBox(height:12),Row(children:[Expanded(child:FilledButton.icon(onPressed:join,icon:const Icon(Icons.person_add),label:const Text('Присоединиться'))),const SizedBox(width:8),Expanded(child:FilledButton.icon(onPressed:toggleTrack,icon:Icon(tracking?Icons.stop:Icons.my_location),label:Text(tracking?'Остановить GPS':'Передавать GPS')))]),const SizedBox(height:16),Text('Задачи',style:Theme.of(c).textTheme.titleLarge),...tasks.map((raw){final t=Map<String,dynamic>.from(raw);return Card(child:ListTile(title:Text(t['title']),subtitle:Text(t['description']??'Без описания'),trailing:DropdownButton<String>(value:t['status'],items:const ['OPEN','IN_PROGRESS','DONE','CANCELLED'].map((x)=>DropdownMenuItem(value:x,child:Text(x))).toList(),onChanged:(v)async{if(v==null)return;try{await widget.api.taskStatus(t['id'],v);}catch(_){await widget.db.enqueue('task',{'taskId':t['id'],'status':v});}load();})));})]));}}
